# Updates README.md whenever `data` branch recieves a push
name: autoupdate

# Runs the job whenever there is a push to `main`
# Since this repo is so small, there is no need for branches thus `on pull`
on:
  push:
    branches:
      - data

# Dispatches a job
jobs:
  build:
    runs-on: ubuntu-latest

    # Moves repo to the runner
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    # Installs Python3.10
    - name: Setups Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    # Gets dependencies
    - name: Installs necessary libraries
      run: pip install numpy scipy sympy

    # Does the dance to update
    - name: Update README
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git fetch
        git pull origin
        git checkout data
        python update.py > README.md
        git add README.md
        git commit -m "Updated README.md with new Ï€ by people estimate"
        git push
        git checkout main
        git merge data
        git push origin
